/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithuchanh4;

import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class NV extends javax.swing.JFrame {
    ArrayList<Nhanvien> lstNV = new ArrayList();
    String manv,phanxuong;
    int sosp;
    /**
     * Creates new form NV
     */
    public NV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtslchuan = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        txtsosp = new javax.swing.JTextField();
        txttienluong = new javax.swing.JTextField();
        combophanxuong = new javax.swing.JComboBox<>();
        btntinh = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btndong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabnv = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã NV");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Số sản phẩm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Phân xưởng");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tiền lương");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Số sản phẩm chuẩn");

        txtslchuan.setEnabled(false);
        txtslchuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtslchuanActionPerformed(evt);
            }
        });

        txttienluong.setBackground(new java.awt.Color(0, 204, 204));
        txttienluong.setEnabled(false);
        txttienluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttienluongActionPerformed(evt);
            }
        });

        combophanxuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        combophanxuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combophanxuongActionPerformed(evt);
            }
        });

        btntinh.setText("Tính lương");
        btntinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btndong.setText("Đóng");
        btndong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndongActionPerformed(evt);
            }
        });

        tabnv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Phân xưởng", "Số sản phẩm", "vượt chuẩn"
            }
        ));
        tabnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabnvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabnv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(combophanxuong, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtslchuan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsosp, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttienluong, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtsosp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combophanxuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtslchuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txttienluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntinh)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnsua)
                    .addComponent(btndong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btntinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhActionPerformed
        // TODO add your handling code here:
        Nhanvien nv = new Nhanvien();
        try{
            manv = txtmanv.getText();
            sosp = Integer.parseInt(txtsosp.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"kiem tra lai thong tin");}
        nv.setPhanxuong(combophanxuong.getSelectedItem().toString()); 
        txtslchuan.setText(String.valueOf(nv.getChuan()));
        nv.setSosp(sosp);
        txttienluong.setText(String.valueOf(nv.tinhluong()));
    }//GEN-LAST:event_btntinhActionPerformed

    private void combophanxuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combophanxuongActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_combophanxuongActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        Nhanvien nv = new Nhanvien();
        try{
            manv = txtmanv.getText();
            sosp = Integer.parseInt(txtsosp.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"kiem tra lai thong tin");
        }
        if (txtmanv.getText().trim().equals("") || txtsosp.getText().trim().equals(""))
           
            JOptionPane.showMessageDialog(this, "Có dữ liệu chưa nhập");
        else{           
            
            nv.setManv(txtmanv.getText());
            nv.setPhanxuong(combophanxuong.getSelectedItem().toString()); }
        //b1: lay data tu các ctrl
        phanxuong = combophanxuong.getSelectedItem().toString();
        //b2 Dua vao list sv
        
        nv.setManv(manv);
        nv.setSosp(sosp);
        nv.setPhanxuong(phanxuong);
        nv.VuotChuan();
        //them vo ds
        lstNV.add(nv);
        //b3: hien len jtable
        //1. tao moi de setModel
        DefaultTableModel model = new DefaultTableModel();
        //1.2 dat ten cho cac cot
        model.addColumn("Mã nhân viên");
        model.addColumn("Phân xưởng");
        model.addColumn("số sản phẩm");
        model.addColumn("Vượt chuẩn");
        //2. duyet araylisst de dua vao model
        for(int i=0; i<lstNV.size();i++)
        {
            Nhanvien NV = lstNV.get(i);
            Vector<String> h = new Vector<>();
            h.add(NV.getManv());
            h.add(NV.getPhanxuong());
            h.add(Integer.toString(NV.getSosp()));
            String c;
            if(NV.VuotChuan()==true)
                c = "X";
            else
                c = "";
            h.add(c);
            model.addRow(h);
        }
        //3. hien ra dieu khien
        tabnv.setModel(model);
        
    }//GEN-LAST:event_btnthemActionPerformed

    private void txtslchuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtslchuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtslchuanActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        //Chọn hàng cần xóa
        int hang=tabnv.getSelectedRow();
        //Hỏi xác nhận xóa
        int kq=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa", "Xác nhận", JOptionPane.WARNING_MESSAGE);
        if(kq==JOptionPane.YES_NO_OPTION)
        //Xóa khỏi List
        lstNV.remove(hang);
        //Cập nhật
        //1.Tạo mới để setModel
        DefaultTableModel model = new DefaultTableModel();
  
        //1.2.Đặt tên cho các cột
        model.addColumn("Mã nhân viên");
        model.addColumn("Phân xưởng");
        model.addColumn("số sản phẩm");
        model.addColumn("Vượt chuẩn");
        //2.Duyệt ArrayList để đưa vào Model
        for(int i=0; i<lstNV.size();i++)
        {
            Nhanvien NV = lstNV.get(i);
            Vector<String> h=new Vector<>();
            h.add(NV.getManv());
            h.add(NV.getPhanxuong());
            h.add(Integer.toString(NV.getSosp()));
            String c;
            if(NV.VuotChuan()==true)
                c = "X";
            else
                c = "";
            h.add(c);
            model.addRow(h);
        }
        //3.Hiện ra điều khiển
        tabnv.setModel(model);
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tabnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabnvMouseClicked
        // TODO add your handling code here:
        //lay ve model
        TableModel mData = tabnv.getModel();
        //lay dong dk chon
        int chon = tabnv.getSelectedRow();
        txtmanv.setText(mData.getValueAt(chon, 0).toString());
        combophanxuong.setSelectedItem(mData.getValueAt(chon, 1).toString());
        txtsosp.setText(mData.getValueAt(chon, 2).toString());
    }//GEN-LAST:event_tabnvMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
       DefaultTableModel model = new DefaultTableModel();
        if(tabnv.getSelectedRow()==-1){    
            if(tabnv.getRowCount()==0) 
                JOptionPane.showMessageDialog(this, "Bảng đang rỗng");
            else
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa");}
        else {
            int yesNo= JOptionPane.showConfirmDialog(this,"Bạn có muốn cập nhật hay không?","Confirm message", JOptionPane.YES_NO_OPTION);

            if (yesNo==0){
                
        Nhanvien nhanvien = new Nhanvien();
        nhanvien.setManv(txtmanv.getText());      
        nhanvien.setPhanxuong(combophanxuong.getSelectedItem().toString());
        nhanvien.setSosp(Integer.parseInt(txtsosp.getText()));    
        TableModel mData = tabnv.getModel();
        // lay dong dk chon de sua
        int chon = tabnv.getSelectedRow();
        //cap nhat lai
        mData.setValueAt(txtmanv.getText(), chon, 0);
        mData.setValueAt(combophanxuong.getSelectedItem().toString(), chon, 1);
        mData.setValueAt(txtsosp.getText(), chon, 2);
        if (nhanvien.VuotChuan())    
            mData.setValueAt("x", tabnv.getSelectedRow(),3);  
        else             
            mData.setValueAt("", tabnv.getSelectedRow(),3);
        
    }//GEN-LAST:event_btnsuaActionPerformed
        }}
    private void btndongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndongActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_btndongActionPerformed

    private void txttienluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttienluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttienluongActionPerformed
       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndong;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btntinh;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> combophanxuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabnv;
    private javax.swing.JTextField txtmanv;
    private javax.swing.JTextField txtslchuan;
    private javax.swing.JTextField txtsosp;
    private javax.swing.JTextField txttienluong;
    // End of variables declaration//GEN-END:variables
}
